### PR TITLE
fix python 3 byte string bug

### PR DESCRIPTION
**Pull request by johnfrancisgit**
Fix error in python3 where there is a typeError thrown in get_errors

### CODE REVIEW

**Comment by zwl1619** [comment]
I download  `pytesseract.py` file to replace the original `pytesseract.py`,and there is an error like this:
```
Traceback (most recent call last):
  File "D:/test.py", line 11, in <module>
    print(pytesseract.image_to_string(Image.open('d:/testimages/name.gif'), lang='chi_sim'))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python35\lib\site-packages\pytesseract\pytesseract.py", line 165, in image_to_string
    raise TesseractError(status, errors)
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \\Program Files (x86)\\Tesseract-OCR\\tessdata/chi_sim.traineddata')
```

**Comment by john-francis96** [comment]
It doesn't seem as though your error is related to this pull request. Does "\\Program Files (x86)\\Tesseract-OCR\\tessdata/chi_sim.traineddata" exist on your system? 
It looks like you can get missing traineddata files from here: https://github.com/tesseract-ocr/tessdata

**Comment by zwl1619** [comment]
@john-francis96 
I have the traineddata that I need.

**Comment by yishangfei** [comment]
image

Is this the problem？？？

**Comment by dickreuter** [comment]
Why Do you need the captchas solver?

**Comment by dickreuter** [comment]
Ignore

**Comment by yishangfei** [comment]
@dickreuter  what?  I'm a beginner

**Comment by int3l** [comment]
Resolved conflicts with this PR, fixed pep8 errors and merging for testing.
Fixes #32

**Pull request merged**
