### PR TITLE
Data class or easier handling of image_to_data() 

### PR DESCRIPTION
**Pull request by Gornoka**
The current implementation of the image_to_data only returns a tsv string  or a dictionary that has to be processed and is not as easy to work with as it could be. This class add's can make it easier to work with the returned information, especially since it enables some of IDE's assistance features.

I hope this is the right format for such a more feature request like thing.

This now also includes some changes in the tests, since otherwise the new feature would not be tested for most python versions.

### CODE REVIEW

**Comment by int3l** [comment]
Hi and thanks for your contribution!
The only problem that I have with the current feature is that it breaks the support for python 2.7 and 3.5 even. And we still support both of those versions (at least on paper).

And while a lot of ppl should switch to python 3.x because Python 2.x is EOL - I am not sure how many ppl use Python 3.6+.

Also, as far as I can see - this implementation relies on tesseract version 5+, which is pretty new and a lot of ppl still use 3.x and 4.x.

So we should consider this before merging such changes.

**Comment by Gornoka** [comment]
Thanks for your quick response.
As far as I see this should work with all Tesseract versions that image_to_data() ( i could only test pytesseract 4.x and 5.x ) supports, however the problem with older python versions still persists

**Comment by Gornoka** [comment]
> Hi and thanks for your contribution!
> The only problem that I have with the current feature is that it breaks the support for python 2.7 and 3.5 even. And we still support both of those versions (at least on paper).
> 
> And while a lot of ppl should switch to python 3.x because Python 2.x is EOL - I am not sure how many ppl use Python 3.6+.
> 
> Also, as far as I can see - this implementation relies on tesseract version 5+, which is pretty new and a lot of ppl still use 3.x and 4.x.
> 
> So we should consider this before merging such changes.

Would this feature be considered useful in general ? 
Right now it seems to work on all python versions on the Xenial Distro, but fails on Bionic. It should now also work on all Tesseract Versions that support the image_to_data() function, but to be honest I have no idea what could be causing the problem on Bionic.

**Comment by int3l** [comment]
Well, we can add this feature as separate install option like `pip install pytesseract[data_object]`
This way everyone that don't have support for the 3.6 stuff for this feature, can skip the installation.

**Comment by Gornoka** [comment]
This version would now work on all required versions of python and tesseract. however i'm wondering why the CI has no tests for tesseract versions larger then 3, since this way all image_to_data tests are skipped.

**Comment by int3l** [comment]
We already have tests for Python 2.7, there is no need to duplicate them with the Bionic builds.
Also Python 2.7 is EOL, so I think that it is a good idea to drop them entirely.
And by the way - it is better to separate the changes in two different PRs.
This PR is for features and not for extending the CI pipeline.

**Comment by Gornoka** [comment]
Okay, thanks for the input, however i considered it necessary to increase the CI pipeline to enable  automated testing of the new feature.

**Comment by int3l** [comment]
It is a good practice, yes. But the free tier is limited and heavy CI pipelines are very likely to fail.

**Pull request closed without merging**
