### PR TITLE
Fixes Attribute Error

### PR DESCRIPTION
**Pull request by amoghbl1**
#15 proposed fix, works and tested on Fedora release 20,
PIL : 1.1.7

### CODE REVIEW

**Comment by madmaze** [comment]
Hi amoghbl1,

Thanks for proposing a fix, but I don't think this will work. It might get past the "number of bands check", but if it does find 4 bands, it will fail on the Image.merge() call since it would try to merge a tuple of strings. 
Also I don't see the issue with your original problem, are you certain that your "img" was not actually a NoneType? 
The actual error is this: 
```
   File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1497, in split
   if self.im.bands == 1:
   AttributeError: 'NoneType' object has no attribute 'bands'
```

Cheers,

madmaze

**Comment by amoghbl1** [comment]
Well, I haven't tested it on an image with 4 bands, let me try that out and update this!
This seems to be a bug in PIL actually, 
test
the split() fails if I try it on this image, but seems to work on another jpg that I tested.

**Comment by madmaze** [comment]
Thanks for the test image, I tried it out and it seems to work. While I am not on Fedora, I am running PIL 1.1.7

Here is the test I just tried:
```
import pytesseract as pt
import Image as im
from PIL import Image as PILim

print pt.image_to_string(im.open("test_img.jpg"))
print pt.image_to_string(PILim.open("test_img.jpg"))
```

output:
```
In [3]: %ed test.py
done. Executing edited code...
% EEEJ. ‘EPu. :rmwni .1
% EEEJ. ‘EPu. :rmwni .1
```

While it fails to properly read the writing, probably because it's handwriting, it does seem to work. For training the OCR for handwriting you may want to take a look here: https://code.google.com/p/tesseract-ocr/wiki/TrainingTesseract3

**Comment by amoghbl1** [comment]
OK, could you try running something like 
'''
from PIL import Image
i = Image.open("/home/amoghbl1/01.jpg")
i.split()
'''
I seem to be getting this error:
'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1497, in split
    if self.im.bands == 1:
AttributeError: 'NoneType' object has no attribute 'bands'
'''
Like I mentioned earlier, seems to be a PIL bug

**Comment by madmaze** [comment]
Hmm yea that is odd, it works for me:

```
In [1]: from PIL import Image
In [2]: i = Image.open("test_img.jpg")
In [3]: i.split()
Out[3]: 
(<PIL.Image.Image image mode=L size=2720x2040 at 0x7F106A15B638>,
 <PIL.Image.Image image mode=L size=2720x2040 at 0x7F106A15B5F0>,
 <PIL.Image.Image image mode=L size=2720x2040 at 0x7F106A15B5A8>)
In [4]: Image.VERSION
Out[4]: '1.1.7
```

That does sound like a bug, somewhere in PIL or its dependencies.
Can you view the image once it's loaded? if not, you may have a problem with libjpeg or somethign
```
In [6]: import pylab
In [7]: pylab.imshow(i)
Out[7]: <matplotlib.image.AxesImage at 0x7f105ac09910>
In [8]: pylab.show()
```

**Comment by amoghbl1** [comment]
Can I find you on IRC somewhere so that we don't make this thread extremely long?

**Comment by madmaze** [comment]
the-gibson on freenode

**Comment by madmaze** [comment]
so this seems like a PIL bug, closing this PR and the Issue #15

**Pull request closed without merging**
