### PR TITLE
Force text column of dataframe to be of string type

### PR DESCRIPTION
**Pull request by mausam3407**
In the cases, where ocr recognizes a decimal value like 0.00 or 1992, dataframe conversion converts the text to 0.0 and 1992.0 which is float type. To maintain the originality of text, I have forced the text column to be of str type.

### CODE REVIEW

**Comment by stefan6419846** [comment]
Could you please add a corresponding test as well?

**Comment by mausam3407** [comment]
@stefan6419846 
Do we want a test case specific to this scenario or just a test case to assert that text column is of str type?

**Comment by stefan6419846** [comment]
We probably should have a test where the common cases are covered, id est the text being a real string in one line and a number in another line.

**Comment by mausam3407** [comment]
@stefan6419846 
This issue is only when ocring over a image which only contains numbers like i have mentioned.

**Comment by stefan6419846** [comment]
Then we should probably have two tests, although one might already exist.

**Comment by mausam3407** [comment]
@stefan6419846 
Hi! I have added the test cases.

**Comment by mausam3407** [comment]
@bozhodimitrov 
Hi! Can you please take a look into this PR?

**Comment by grantrosse** [comment]
you can use the pandas_config parameter of image_to_data() to pass the argument to the embedded read_csv():
`df = pytesseract.image_to_data(image, lang=, output_type='data.frame', config=, pandas_config={'dtype': {'text': str}})`

**Pull request closed without merging**
