### PR TITLE
Improve and fix CI

### PR DESCRIPTION
**Pull request by egeakman**
Updates:
- Test the installation of the commit/PR (the version we checked out with actions/checkout) instead of testing the default branch of the repo. With this, we can actually test pull requests.
- Test all commits and PRs regardless of branch name.
- Add option to dispatch the workflow manually.

### CODE REVIEW

**Comment by egeakman** [comment]
Kindly pinging @bozhodimitrov

**Comment by bozhodimitrov** [comment]
To be honest, we should use pre-commit's setup entirely to avoid the current mess (which doesn't even include testing on windows at all)

https://github.com/pre-commit/pre-commit/blob/main/.github/workflows/main.yml

But for now, there is no much point for major changes since the owner of this repository is busy and PyPi updates are not possible anyways.

**Comment by bozhodimitrov** [comment]
Also, I don't think that it's a good idea to allow checks on everything.

**Comment by egeakman** [comment]
Hi, thanks for getting back!

About the owner not being available, I believe that poses a significant drag on the project. The last release on PyPI was about one and a half years ago and that discourages potential contributors from contributing. So, I have a few questions:

- [Is he reachable? ](https://peps.python.org/pep-0541/#reachability)

If he is, would he consider:
- Giving full permissions to @bozhodimitrov (or another active maintainer) on this repository
- Adding @bozhodimitrov (or another active maintainer) to the maintainers list in the project metadata, so you can release on PyPI

If he is not, this project is eligible for the implementation of [PEP 541](https://peps.python.org/pep-0541/#implementation).

---

***Quoting PEP 541:***

### [Reachability](https://peps.python.org/pep-0541/#reachability)

The user of the Package Index is solely responsible for being reachable by the Package Index maintainers for matters concerning projects that the user owns. In every case where contacting the user is necessary, the maintainers will try to do so at least three times, using the following means of contact:

- the e-mail address on file in the user’s profile on the Package Index;
- the e-mail address listed in the Author field for a given project uploaded to the Index; and
- any e-mail addresses found in the given project’s documentation on the Index or on the listed Home Page.

The maintainers stop trying to reach the user after six weeks.

### [Abandoned projects](https://peps.python.org/pep-0541/#abandoned-projects)

A project is considered abandoned when ALL of the following are met:

- owner not reachable (see Reachability above);
- no releases within the past twelve months; and
- no activity from the owner on the project’s home page (or no home page listed).

All other projects are considered active.

### [Continued maintenance of an abandoned project](https://peps.python.org/pep-0541/#continued-maintenance-of-an-abandoned-project)

If a candidate appears willing to continue maintenance on an abandoned project, ownership of the name is transferred when ALL of the following are met:

- the project has been determined abandoned by the rules described above;
- the candidate is able to demonstrate their own failed attempts to contact the existing owner;
- the candidate is able to demonstrate improvements made on the candidate’s own fork of the project;
- the candidate is able to demonstrate why a fork under a different name is not an acceptable workaround; and
- the maintainers of the Package Index don’t have any additional reservations.

Under no circumstances will a name be reassigned against the wishes of a reachable owner.

**Comment by egeakman** [comment]
I can open a separate issue to further discuss the maintenance of this project. Please let me know.

**Comment by bozhodimitrov** [comment]
This project is not mine, so I can't discuss such stuff. I am just a volunteer like you and everyone else who wanted to help with the project. Unfortunately people have limited time for such projects and it affects the development. This is not uncommon for the OSS repositories.

I understand your enthusiasm and drive to help, but please keep in mind that maintaining a project is a responsibility. And the bigger project means bigger responsibility.
And I am not talking just for the technical perspective.

So, yes. If you want to raise such issue, go for it.
It is always better to have such stuff separate, so they can be addressed individually and the discussions can be on topic.

**Pull request merged**
