### PR TITLE
added orientation method and enabled to set the psm mode

### PR DESCRIPTION
**Pull request by JeffreyBouva**
He guys,

I've added a method that will give back the orientation of the image.
Also i've added the normally 2 new lines before every method and enabled the usage of a psm mode.

I hope you guys can use my work and i'm very happy with yours! 

Thank you!

### CODE REVIEW

**Comment by madmaze** [comment]
Thanks, at first glance these changes look great, I'll take a closer look this evening

**Comment by madmaze** [comment]
Hi @JeffreyBouva,

Thanks for the pull request, I looked it over more carefully and while your implementation is clean and well formatted(thanks for the formatting fixes), I would like to see less of the image_to_string() function duplicated in get_image_orientation(). Perhaps get_image_orientation() could be a wrapper for image_to_string() which sets an argument to only retrieve the orientation.

Thanks,

madmaze

**Comment by JeffreyBouva** [comment]
Hi @madmaze Thank you for your feedback on the code. I will take a look at it. Very happy with your project and  your help!

**Comment by kyle-sorensen** [comment]
This pull request breaks if you use -psm 0, because this method by tesseract does not write the results to a temp file, so it will throw a file not found exception.

**Pull request closed without merging**
