### PR TITLE
Improved method to discard alpha channel

### PR DESCRIPTION
**Pull request by jsreid13**
Changed the current method that uses split with the faster convert
method within PIL Image object

### CODE REVIEW

**Comment by int3l** [comment]
Hi @jsreid13 , thank you for the improvement.
I noticed that we can do even better.

**Comment by jsreid13** [comment]
Can you elaborate on what you have in mind?

**Comment by int3l** [comment]
For example, we can change this section:
``` diff python
- if len(image.split()) == 4:
+ if len(image.getbands()) == 4:
    image.convert('RGB')

```

But we need to test it in order to be sure, that it produce the same result.
For example, it can be tested with image that has Alpha channel and with one that doesn't :)

**Comment by jsreid13** [comment]
Using split the time is 0.00643s and the if statement catches 4 channel images and ignores 3 channel or fewer images, tested with the image linked in my issue post for the 4 channel image and the following image for the 3 channel image:
telidon font

Using getbands the time is 0.00521s, so a definite improvement and it also successfully skips the 3 channel image and catches the 4 channel image. It also skips this one channel image.
6_cleaned

I've pushed this change to this branch.

**Comment by int3l** [comment]
Fixes #81

**Pull request merged**
