### PR TITLE
add oem variable

### PR DESCRIPTION
**Pull request by roya0045**
Greetings, this is a quick draft/WIP.

The goal is mostly to add the ability to select the engine for tesseract 4.0.

 Any comments/ suggestions are welcome.

### CODE REVIEW

**Comment by int3l** [comment]
Hi @roya0045 
thanks for contributing.
I couple of things:
1. You can add --oem via the **config** argument of pytesseract and this is considered additional option.
2. The way you add this is not correct since it will add the flag after the configfiles at the end of the command which is not supported by tesseract itself.

**Comment by roya0045** [comment]
@int3l is it the same case for `psm` also?

**Comment by int3l** [comment]
Yes, basically we have **config** in order to pass all custom options to tessseract.
At the moment there is no need to add the individual options one by one.
Function signatures will get very long.

**Comment by roya0045** [comment]
@int3l My bad, I thought config was to set up training folder and not extra arguments. I'll close this PR, sorry for the trouble.

**Comment by int3l** [comment]
I can update the README docs with examples for that.

**Comment by roya0045** [comment]
TBH it's mostly the phrase "Add the following config, if you have tessdata error like: "Error opening data file..." that made me think that config was actually to configure the tesseract execution and not to also pass extra paramaters as stated in the doc. The fault is on me as I have simply checked the examples.

Though a good improvement would be to change that phrase to something like:
 " The config keword can also be used to add any element to the command. Such as `oem`, `psm` and others. Here we are adding the following config, if you have tessdata error like: "Error opening data file..."

**Comment by roya0045** [comment]
@int3l That example should be sufficient to show the use and syntax. Thanks!

**Pull request closed without merging**
